### ISSUE TITLE
multiple session break console output

### ISSUE THREAD

**Issue by RamadhanAmizudin** [brightio/penelope#10] opened 2022-03-17 17:49 UTC
Hi,

First of all, this tool is amazing. Right now i facing weird issue is that the console just simply messed up after receiving more than 2 connection. 

I attached screenshot to visually describe the issue
![Capture](https://user-images.githubusercontent.com/2631784/158864326-9a658e9f-eb26-4fa5-8b02-131accd11d11.PNG)

thank you!

**Comment by brightio** [comment] 2022-03-17 23:45
Hi @RamadhanAmizudin, thank you very much for reporting that issue! Can you please help me to reproduce it because I can't? (Does it happen every time? Which version you use? What is your OS? etc)

**Comment by RamadhanAmizudin** [comment] 2022-03-18 05:41
Hi, I started penelope with following arg
`python3 penelope.py -C -H -a 9999`
and use one of the hint to spawn first connection, and then interact with 1, after than start additional connection (normally after 2 connection, the console start acting weird).
It happen everytime I received multiple connection.

OS: Ubuntu 20 (VPS) and ubuntu wsl
Python Version:  Python 3.8.2

hope thats help!

**Comment by brightio** [comment] 2022-03-18 08:23
That helped me to spot the bug, thank you! The problem is with the -C switch and introduced in the main branch after the last release. I will work on a fix soon.

**Comment by brightio** [comment] 2022-05-05 13:08
I delayed it a bit but now it should be fixed. Thank you very much @RamadhanAmizudin for this!

**Closed by brightio** 2022-05-05 13:08 UTC
Labels: bug
