### ISSUE TITLE
SyntaxWarning Message

### ISSUE THREAD

**Issue by JLowborn** [brightio/penelope#24] opened 2024-07-16 15:43 UTC
After running the program, it shows a `SyntaxWarning` message due to an invalid escape sequence on the code. This can, although, be considered a minor error, since it doesn't interfere during the usage.

![image](https://github.com/user-attachments/assets/583e5f6d-c77a-42d4-86ec-f8d2c7266c63)

**Comment by stavoxnetworks** [comment] 2024-07-19 00:18
This can be corrected by changing line 3008 to :

`output = re.sub(r'\n\s', ' ', subprocess.check_output(['ifconfig']).decode())
`


Its caused by the 3.12 version of Python3

![image](https://github.com/user-attachments/assets/c890cc7f-4202-49cd-b4e1-0bc84afb6c63)

**Comment by brightio** [comment] 2024-08-31 08:54
Thanks a lot guys for reporting this! This already had been fixed in the `dev` branch (commit 4d0c7f8) which is now merged into `main`.

**Closed by brightio** 2024-08-31 08:54 UTC
